window.PERFORMANCE_ACADEMIA = {
  nome: "Performance Academia",
  cidade: "Estreito — MA",
  endereco: "R. Santos Dumont, 635",
  bairro: "",
  cep: "65975-000",
  telefone: "(99) 98156-8022",
  telefoneE164: "5599981568022",
  instagram: "academia_performancee",
  avaliacao: "5,0",
  whatsappTexto: "Olá! Gostaria de conhecer a Performance Academia.",
  galeria: [
    { src: "img/galeria-1.jpg", alt: "Frente da Performance Academia em Estreito" },
    { src: "img/galeria-2.jpg", alt: "Vitrine e equipamentos da Performance Academia" },
    { src: "img/galeria-3.jpg", alt: "Área de cardio vista da fachada da Performance Academia" },
    { src: "img/galeria-4.jpg", alt: "Entrada da Performance Academia" },
    { src: "img/galeria-5.jpg", alt: "Letreiro da Performance Academia" },
  ],
  instagramFeed: [
    { src: "img/instagram-1.jpg", alt: "Frente da Performance Academia" },
    { src: "img/instagram-2.jpg", alt: "Fachada da Performance Academia" },
    { src: "img/instagram-3.jpg", alt: "Equipamentos na vitrine da Performance Academia" },
    { src: "img/instagram-4.jpg", alt: "Entrada da Performance Academia" },
    { src: "img/instagram-5.jpg", alt: "Letreiro da Performance Academia" },
    { src: "img/instagram-6.jpg", alt: "Performance Academia em Estreito" },
  ],
  horarios: {
    1: [{ abre: "05:30", fecha: "10:30" }, { abre: "14:00", fecha: "21:30" }],
    2: [{ abre: "05:30", fecha: "10:30" }, { abre: "14:00", fecha: "21:30" }],
    3: [{ abre: "05:30", fecha: "10:30" }, { abre: "14:00", fecha: "21:30" }],
    4: [{ abre: "05:30", fecha: "10:30" }, { abre: "14:00", fecha: "21:30" }],
    5: [{ abre: "05:30", fecha: "10:30" }, { abre: "14:00", fecha: "21:30" }],
    6: [{ abre: "06:00", fecha: "10:00" }, { abre: "15:30", fecha: "18:30" }],
  },
};
