window.CASA_DO_RIO = {
  nome: "Casa do Rio",
  slogan: "Cozinha brasileira à beira do Tocantins",
  cidade: "Estreito — MA",
  endereco: "Avenida Beira Rio",
  bairro: "Beira Rio",
  cep: "65975-000",
  referencia: "Às margens do Rio Tocantins",
  telefone: "(99) 99999-0000",
  telefoneE164: "5599999990000",
  instagram: "casadorio.estreito",
  avaliacao: "4,8",
  avaliacoes: "36",
  whatsappTexto: "Olá! Conheci a Casa do Rio pelo site e gostaria de fazer uma reserva.",
  mapaQuery: "Avenida Beira Rio, Estreito, Maranhão",
  horarios: {
    0: [{ abre: "11:00", fecha: "15:00" }, { abre: "18:00", fecha: "23:00" }],
    1: [],
    2: [{ abre: "11:00", fecha: "15:00" }, { abre: "18:00", fecha: "23:00" }],
    3: [{ abre: "11:00", fecha: "15:00" }, { abre: "18:00", fecha: "23:00" }],
    4: [{ abre: "11:00", fecha: "15:00" }, { abre: "18:00", fecha: "23:00" }],
    5: [{ abre: "11:00", fecha: "15:00" }, { abre: "18:00", fecha: "23:30" }],
    6: [{ abre: "11:00", fecha: "15:00" }, { abre: "18:00", fecha: "23:30" }],
  },
  cardapio: [
    {
      id: "entradas",
      nome: "Entradas",
      foto: "img/entrada.jpg",
      fotoWebp: "img/entrada.webp",
      itens: [
        { nome: "Isca de peixe com vinagrete", desc: "Filés empanados, limão e vinagrete da casa.", preco: 38 },
        { nome: "Bolinho de arroz com queijo coalho", desc: "Crocante por fora, queijo derretido por dentro.", preco: 28 },
        { nome: "Caldinho de peixe", desc: "Receita do rio, com coentro e pimenta-de-cheiro.", preco: 22 },
        { nome: "Dadinho de tapioca", desc: "Servido com geleia de pimenta.", preco: 26 },
      ],
    },
    {
      id: "peixes",
      nome: "Peixes do rio",
      foto: "img/peixe.jpg",
      fotoWebp: "img/peixe.webp",
      itens: [
        { nome: "Tambaqui na brasa", desc: "Costela de tambaqui, farofa e vinagrete.", preco: 89 },
        { nome: "Filé de pintado ao molho de camarão", desc: "Arroz soltinho e legumes na manteiga.", preco: 96 },
        { nome: "Moqueca de peixe do rio", desc: "Para 2 pessoas. Dendê, leite de coco e pirão.", preco: 148 },
        { nome: "Peixe frito inteiro", desc: "Acompanha arroz, feijão e salada.", preco: 78 },
      ],
    },
    {
      id: "carnes",
      nome: "Carnes",
      foto: "img/carnes.jpg",
      fotoWebp: "img/carnes.webp",
      itens: [
        { nome: "Picanha na chapa", desc: "Ponto à sua escolha, arroz, farofa e vinagrete.", preco: 92 },
        { nome: "Carne de sol com mandioca", desc: "Manteiga de garrafa e cebola caramelizada.", preco: 68 },
        { nome: "Costela assada", desc: "Lenta, suculenta, com mandioca frita.", preco: 86 },
        { nome: "Frango caipira ao molho", desc: "Arroz com pequi e salada da casa.", preco: 54 },
      ],
    },
    {
      id: "casa",
      nome: "Pratos da casa",
      foto: "img/pratos.jpg",
      fotoWebp: "img/pratos.webp",
      itens: [
        { nome: "Arroz com pequi e frango", desc: "Sabor do cerrado com toque da casa.", preco: 54 },
        { nome: "Feijão tropeiro", desc: "Bacon, ovo, couve e farinha.", preco: 42 },
        { nome: "Executivo do almoço", desc: "Prato do dia. Consulte pelo WhatsApp.", preco: 32 },
        { nome: "Porção família", desc: "Peixe ou carne para 3 a 4 pessoas.", preco: 159 },
      ],
    },
    {
      id: "sobremesas",
      nome: "Sobremesas",
      foto: "img/sobremesa.jpg",
      fotoWebp: "img/sobremesa.webp",
      itens: [
        { nome: "Pudim da casa", desc: "Receita clássica, calda morna.", preco: 18 },
        { nome: "Doce de leite com queijo", desc: "Casamento mineiro na dose certa.", preco: 16 },
        { nome: "Açaí com granola", desc: "Cremoso, banana e mel.", preco: 22 },
        { nome: "Cartola", desc: "Banana, queijo e canela.", preco: 20 },
      ],
    },
    {
      id: "bebidas",
      nome: "Bebidas",
      foto: "img/bebidas.jpg",
      fotoWebp: "img/bebidas.webp",
      itens: [
        { nome: "Suco de caju", desc: "Natural, copo 400 ml.", preco: 12 },
        { nome: "Caipirinha da casa", desc: "Limão, caju ou maracujá.", preco: 18 },
        { nome: "Cerveja gelada", desc: "Long neck. Consulte marcas.", preco: 10 },
        { nome: "Água de coco", desc: "Natural, gelada.", preco: 8 },
      ],
    },
  ],
};
