import type { LucideIcon } from "lucide-react";
import {
  ArrowDownCircle,
  ArrowLeftRight,
  ArrowUpCircle,
  BadgeCheck,
  BarChart3,
  Bike,
  ClipboardList,
  CreditCard,
  History,
  LayoutDashboard,
  LayoutGrid,
  Lock,
  Package,
  PackageSearch,
  Receipt,
  ScrollText,
  Settings,
  Shield,
  ShoppingBag,
  SquareTerminal,
  Store,
  Ticket,
  UserCog,
  Users,
  UtensilsCrossed,
  Wallet,
} from "lucide-react";

const ICONS: Record<string, LucideIcon> = {
  "/app": LayoutDashboard,
  "/admin": Shield,
  "/admin/tenants": Store,
  "/admin/users": Users,
  "/admin/plans": Ticket,
  "/admin/audit": ScrollText,
  "/admin/acompanhamento": PackageSearch,
  "/caixa": Wallet,
  "/caixa/pdv": SquareTerminal,
  "/caixa/pedidos": ClipboardList,
  "/caixa/pagamentos": CreditCard,
  "/caixa/mesas": LayoutGrid,
  "/caixa/clientes": Users,
  "/caixa/movimentacoes": ArrowLeftRight,
  "/caixa/sangria": ArrowDownCircle,
  "/caixa/suprimento": ArrowUpCircle,
  "/caixa/despesa": Receipt,
  "/caixa/conferencia": BadgeCheck,
  "/caixa/fechamento": Lock,
  "/caixa/turno": Wallet,
  "/caixa/historico": History,
  "/caixa/estoque": Package,
  "/caixa/conta": UserCog,
  "/app/pedidos": ClipboardList,
  "/app/salao": LayoutGrid,
  "/app/cozinha": UtensilsCrossed,
  "/app/entregas": Bike,
  "/entrega": Bike,
  "/entrega/pedidos": ClipboardList,
  "/garcom": ShoppingBag,
  "/app/clientes": Users,
  "/app/cupons": Ticket,
  "/app/cardapio": Store,
  "/app/estoque": Package,
  "/app/caixas": Wallet,
  "/app/caixas/relatorios": BarChart3,
  "/app/caixas/terminais": SquareTerminal,
  "/app/financeiro": Receipt,
  "/app/relatorios": BarChart3,
  "/app/equipe": UserCog,
  "/app/auditoria": ScrollText,
  "/app/configuracoes": Settings,
  "/app/ajuda": ScrollText,
};

export function navIcon(href: string): LucideIcon {
  return ICONS[href] ?? LayoutDashboard;
}
