from app.routes.auth import auth_bp
from app.routes.dashboard import dashboard_bp
from app.routes.movimentacoes import movimentacoes_bp
from app.routes.comprovantes import comprovantes_bp
from app.routes.contas import contas_bp
from app.routes.categorias import categorias_bp
from app.routes.configuracoes import configuracoes_bp
from app.routes.pesquisa import pesquisa_bp
from app.routes.vencimentos import vencimentos_bp
from app.routes.recorrencias import recorrencias_bp
from app.routes.relatorios import relatorios_bp
from app.routes.cartoes import cartoes_bp
from app.routes.orcamentos import orcamentos_bp
from app.routes.assinatura import assinatura_bp
