window.ACTION_FITNESS = {
  nome: "Action Fitness",
  cidade: "Estreito — MA",
  endereco: "Avenida Chico Brito, 1006",
  bairro: "Centro",
  cep: "65975-000",
  referencia: "Próxima à Praça da Bíblia",
  telefone: "(99) 99234-8793",
  telefoneE164: "5599992348793",
  instagram: "actionfitness_academia",
  avaliacao: "4,9",
  avaliacoes: "47",
  whatsappTexto: "Olá! Conheci a Action Fitness pelo site e gostaria de saber mais sobre os planos.",
  planos: [
    { nome: "Mensal", valor: "Consulte condições" },
    { nome: "Trimestral", valor: "Consulte condições" },
    { nome: "Semestral", valor: "Consulte condições" },
    { nome: "Anual", valor: "Consulte condições" },
  ],
  galeria: [
    { src: "img/galeria-1.jpg", alt: "Frente da Action Fitness em Estreito" },
    { src: "img/galeria-2.jpg", alt: "Área de musculação da Action Fitness" },
    { src: "img/galeria-3.jpg", alt: "Ambiente da academia em Estreito" },
    { src: "img/galeria-4.jpg", alt: "Equipe e estrutura da Action Fitness" },
    { src: "img/galeria-5.jpg", alt: "Espaço de treino da Action Fitness" },
  ],
  instagramFeed: [
    { src: "img/instagram-1.jpg", alt: "Horários da Action Fitness no Instagram" },
    { src: "img/instagram-2.jpg", alt: "Publicação da Action Fitness" },
    { src: "img/instagram-3.jpg", alt: "Equipe da Action Fitness" },
    { src: "img/instagram-4.jpg", alt: "Publicação da Action Fitness" },
    { src: "img/instagram-5.jpg", alt: "Novas máquinas na Action Fitness" },
    { src: "img/instagram-6.jpg", alt: "Estrutura da Action Fitness" },
  ],
  horarios: {
    1: [{ abre: "05:30", fecha: "22:30" }],
    2: [{ abre: "05:30", fecha: "22:30" }],
    3: [{ abre: "05:30", fecha: "22:30" }],
    4: [{ abre: "05:30", fecha: "22:30" }],
    5: [{ abre: "05:30", fecha: "22:30" }],
    6: [
      { abre: "06:00", fecha: "10:00" },
      { abre: "15:00", fecha: "19:00" },
    ],
    0: [{ abre: "15:00", fecha: "19:00" }],
  },
};
